/**
 * 메가캡 우량주 모니터 — 유니버스 후보 풀
 *
 * Yahoo Finance 티커 기준. 시장별 시총 상위 자동 선정의 1차 후보.
 * 분기별 1회 수동 갱신 권장. 새 메가캡 등장 시 추가, 합병/상폐 시 제거.
 */

export interface UniverseCandidate {
  ticker: string;        // Yahoo Finance 티커
  name_kr: string;       // 한국어 표시명
  market: "US" | "KR" | "JP" | "CN" | "EU" | "OTHER";
  currency: "USD" | "KRW" | "JPY" | "CNY" | "HKD" | "EUR" | "TWD" | "INR" | "GBP" | "BRL" | "MXN" | "AUD" | "CAD" | "SGD";
  sector?: string;       // 대분류 섹터
}

// ── 시장별 쿼터 (각 시장별 메가캡 시총 상위 100위까지 자동 선정) ──
// 후보 풀이 더 적은 시장은 가용한 만큼만 채워짐
export const MARKET_QUOTAS: Record<UniverseCandidate["market"], number> = {
  US: 100,
  KR: 100,
  JP: 100,
  CN: 100,
  EU: 100,
  OTHER: 100,
};

// ── 미국 메가캡 후보 (시총 큰 기업 위주) ──
const US: UniverseCandidate[] = [
  { ticker: "AAPL", name_kr: "애플", market: "US", currency: "USD", sector: "Technology" },
  { ticker: "MSFT", name_kr: "마이크로소프트", market: "US", currency: "USD", sector: "Technology" },
  { ticker: "GOOGL", name_kr: "알파벳(A)", market: "US", currency: "USD", sector: "Communication" },
  { ticker: "AMZN", name_kr: "아마존", market: "US", currency: "USD", sector: "Consumer Discretionary" },
  { ticker: "NVDA", name_kr: "엔비디아", market: "US", currency: "USD", sector: "Technology" },
  { ticker: "META", name_kr: "메타", market: "US", currency: "USD", sector: "Communication" },
  { ticker: "BRK-B", name_kr: "버크셔해서웨이(B)", market: "US", currency: "USD", sector: "Financials" },
  { ticker: "V", name_kr: "비자", market: "US", currency: "USD", sector: "Financials" },
  { ticker: "MA", name_kr: "마스터카드", market: "US", currency: "USD", sector: "Financials" },
  { ticker: "JPM", name_kr: "JP모건", market: "US", currency: "USD", sector: "Financials" },
  { ticker: "JNJ", name_kr: "존슨앤드존슨", market: "US", currency: "USD", sector: "Healthcare" },
  { ticker: "WMT", name_kr: "월마트", market: "US", currency: "USD", sector: "Consumer Staples" },
  { ticker: "PG", name_kr: "P&G", market: "US", currency: "USD", sector: "Consumer Staples" },
  { ticker: "UNH", name_kr: "유나이티드헬스", market: "US", currency: "USD", sector: "Healthcare" },
  { ticker: "HD", name_kr: "홈디포", market: "US", currency: "USD", sector: "Consumer Discretionary" },
  { ticker: "KO", name_kr: "코카콜라", market: "US", currency: "USD", sector: "Consumer Staples" },
  { ticker: "PEP", name_kr: "펩시코", market: "US", currency: "USD", sector: "Consumer Staples" },
  { ticker: "COST", name_kr: "코스트코", market: "US", currency: "USD", sector: "Consumer Staples" },
  { ticker: "AVGO", name_kr: "브로드컴", market: "US", currency: "USD", sector: "Technology" },
  { ticker: "XOM", name_kr: "엑손모빌", market: "US", currency: "USD", sector: "Energy" },
  { ticker: "ORCL", name_kr: "오라클", market: "US", currency: "USD", sector: "Technology" },
  { ticker: "MCD", name_kr: "맥도날드", market: "US", currency: "USD", sector: "Consumer Discretionary" },
  { ticker: "MRK", name_kr: "머크", market: "US", currency: "USD", sector: "Healthcare" },
  { ticker: "BAC", name_kr: "뱅크오브아메리카", market: "US", currency: "USD", sector: "Financials" },
  { ticker: "ABBV", name_kr: "애브비", market: "US", currency: "USD", sector: "Healthcare" },
  { ticker: "NKE", name_kr: "나이키", market: "US", currency: "USD", sector: "Consumer Discretionary" },
  { ticker: "CRM", name_kr: "세일즈포스", market: "US", currency: "USD", sector: "Technology" },
  { ticker: "ACN", name_kr: "액센추어", market: "US", currency: "USD", sector: "Technology" },
  { ticker: "CSCO", name_kr: "시스코", market: "US", currency: "USD", sector: "Technology" },
  { ticker: "PFE", name_kr: "화이자", market: "US", currency: "USD", sector: "Healthcare" },
  { ticker: "INTC", name_kr: "인텔", market: "US", currency: "USD", sector: "Technology" },
  { ticker: "WFC", name_kr: "웰스파고", market: "US", currency: "USD", sector: "Financials" },
  { ticker: "NFLX", name_kr: "넷플릭스", market: "US", currency: "USD", sector: "Communication" },
  { ticker: "AMD", name_kr: "AMD", market: "US", currency: "USD", sector: "Technology" },
  { ticker: "TXN", name_kr: "텍사스인스트루먼트", market: "US", currency: "USD", sector: "Technology" },
  { ticker: "IBM", name_kr: "IBM", market: "US", currency: "USD", sector: "Technology" },
  { ticker: "MS", name_kr: "모건스탠리", market: "US", currency: "USD", sector: "Financials" },
  { ticker: "CMCSA", name_kr: "컴캐스트", market: "US", currency: "USD", sector: "Communication" },
  { ticker: "ADBE", name_kr: "어도비", market: "US", currency: "USD", sector: "Technology" },
  { ticker: "GS", name_kr: "골드만삭스", market: "US", currency: "USD", sector: "Financials" },
  { ticker: "RTX", name_kr: "RTX", market: "US", currency: "USD", sector: "Industrials" },
  { ticker: "GE", name_kr: "GE에어로스페이스", market: "US", currency: "USD", sector: "Industrials" },
  { ticker: "AMGN", name_kr: "암젠", market: "US", currency: "USD", sector: "Healthcare" },
  { ticker: "BMY", name_kr: "BMS", market: "US", currency: "USD", sector: "Healthcare" },
  { ticker: "BA", name_kr: "보잉", market: "US", currency: "USD", sector: "Industrials" },
  { ticker: "CAT", name_kr: "캐터필러", market: "US", currency: "USD", sector: "Industrials" },
  { ticker: "AXP", name_kr: "아메리칸익스프레스", market: "US", currency: "USD", sector: "Financials" },
  { ticker: "BLK", name_kr: "블랙록", market: "US", currency: "USD", sector: "Financials" },
  { ticker: "SCHW", name_kr: "찰스슈왑", market: "US", currency: "USD", sector: "Financials" },
  { ticker: "CVX", name_kr: "셰브론", market: "US", currency: "USD", sector: "Energy" },
  { ticker: "LIN", name_kr: "린데", market: "US", currency: "USD", sector: "Materials" },
  { ticker: "NOW", name_kr: "서비스나우", market: "US", currency: "USD", sector: "Technology" },
  { ticker: "DHR", name_kr: "다나허", market: "US", currency: "USD", sector: "Healthcare" },
  { ticker: "BKNG", name_kr: "부킹홀딩스", market: "US", currency: "USD", sector: "Consumer Discretionary" },
  { ticker: "ELV", name_kr: "엘리번스헬스", market: "US", currency: "USD", sector: "Healthcare" },
  { ticker: "SBUX", name_kr: "스타벅스", market: "US", currency: "USD", sector: "Consumer Discretionary" },
  { ticker: "MDT", name_kr: "메드트로닉", market: "US", currency: "USD", sector: "Healthcare" },
  { ticker: "ISRG", name_kr: "인튜이티브서지컬", market: "US", currency: "USD", sector: "Healthcare" },
  { ticker: "INTU", name_kr: "인튜이트", market: "US", currency: "USD", sector: "Technology" },
  { ticker: "AMT", name_kr: "아메리칸타워", market: "US", currency: "USD", sector: "Real Estate" },
  { ticker: "GILD", name_kr: "길리어드", market: "US", currency: "USD", sector: "Healthcare" },
  { ticker: "MMC", name_kr: "마쉬앤맥레넌", market: "US", currency: "USD", sector: "Financials" },
  { ticker: "ZTS", name_kr: "조에티스", market: "US", currency: "USD", sector: "Healthcare" },
  { ticker: "VRTX", name_kr: "버텍스", market: "US", currency: "USD", sector: "Healthcare" },
  { ticker: "REGN", name_kr: "리제네론", market: "US", currency: "USD", sector: "Healthcare" },
  { ticker: "LRCX", name_kr: "램리서치", market: "US", currency: "USD", sector: "Technology" },
  { ticker: "ADI", name_kr: "아날로그디바이스", market: "US", currency: "USD", sector: "Technology" },
  { ticker: "KLAC", name_kr: "KLA", market: "US", currency: "USD", sector: "Technology" },
  { ticker: "EQIX", name_kr: "에퀴닉스", market: "US", currency: "USD", sector: "Real Estate" },
  { ticker: "ANET", name_kr: "아리스타네트웍스", market: "US", currency: "USD", sector: "Technology" },
  { ticker: "ADP", name_kr: "ADP", market: "US", currency: "USD", sector: "Industrials" },
  { ticker: "TJX", name_kr: "TJX", market: "US", currency: "USD", sector: "Consumer Discretionary" },
  { ticker: "PGR", name_kr: "프로그레시브", market: "US", currency: "USD", sector: "Financials" },
  { ticker: "ICE", name_kr: "인터컨티넨탈익스체인지", market: "US", currency: "USD", sector: "Financials" },
  { ticker: "MO", name_kr: "알트리아", market: "US", currency: "USD", sector: "Consumer Staples" },
  { ticker: "MCO", name_kr: "무디스", market: "US", currency: "USD", sector: "Financials" },
  { ticker: "BDX", name_kr: "벡톤디킨슨", market: "US", currency: "USD", sector: "Healthcare" },
  { ticker: "MMM", name_kr: "3M", market: "US", currency: "USD", sector: "Industrials" },
  { ticker: "SYK", name_kr: "스트라이커", market: "US", currency: "USD", sector: "Healthcare" },
  { ticker: "LLY", name_kr: "일라이릴리", market: "US", currency: "USD", sector: "Healthcare" },
  { ticker: "TSLA", name_kr: "테슬라", market: "US", currency: "USD", sector: "Consumer Discretionary" },
  { ticker: "PLTR", name_kr: "팔란티어", market: "US", currency: "USD", sector: "Technology" },
  { ticker: "ABT", name_kr: "애보트", market: "US", currency: "USD", sector: "Healthcare" },
  { ticker: "CRWD", name_kr: "크라우드스트라이크", market: "US", currency: "USD", sector: "Technology" },
  { ticker: "PANW", name_kr: "팔로알토네트웍스", market: "US", currency: "USD", sector: "Technology" },
  { ticker: "QCOM", name_kr: "퀄컴", market: "US", currency: "USD", sector: "Technology" },
  { ticker: "AMAT", name_kr: "어플라이드머티리얼즈", market: "US", currency: "USD", sector: "Technology" },
  { ticker: "MU", name_kr: "마이크론", market: "US", currency: "USD", sector: "Technology" },
  { ticker: "MRVL", name_kr: "마벨", market: "US", currency: "USD", sector: "Technology" },
  { ticker: "SNPS", name_kr: "시놉시스", market: "US", currency: "USD", sector: "Technology" },
  { ticker: "CDNS", name_kr: "케이던스", market: "US", currency: "USD", sector: "Technology" },
  { ticker: "WDAY", name_kr: "워크데이", market: "US", currency: "USD", sector: "Technology" },
  { ticker: "TEAM", name_kr: "아틀라시안", market: "US", currency: "USD", sector: "Technology" },
  { ticker: "DDOG", name_kr: "데이터독", market: "US", currency: "USD", sector: "Technology" },
  { ticker: "SHOP", name_kr: "쇼피파이", market: "US", currency: "USD", sector: "Technology" },
  { ticker: "UBER", name_kr: "우버", market: "US", currency: "USD", sector: "Consumer Discretionary" },
  { ticker: "ABNB", name_kr: "에어비앤비", market: "US", currency: "USD", sector: "Consumer Discretionary" },
  { ticker: "DIS", name_kr: "월트디즈니", market: "US", currency: "USD", sector: "Communication" },
  { ticker: "T", name_kr: "AT&T", market: "US", currency: "USD", sector: "Communication" },
  { ticker: "VZ", name_kr: "버라이즌", market: "US", currency: "USD", sector: "Communication" },
  { ticker: "TMUS", name_kr: "T-Mobile", market: "US", currency: "USD", sector: "Communication" },
  { ticker: "F", name_kr: "포드", market: "US", currency: "USD", sector: "Consumer Discretionary" },
  { ticker: "GM", name_kr: "GM", market: "US", currency: "USD", sector: "Consumer Discretionary" },
  { ticker: "C", name_kr: "씨티그룹", market: "US", currency: "USD", sector: "Financials" },
  { ticker: "USB", name_kr: "US뱅코프", market: "US", currency: "USD", sector: "Financials" },
  { ticker: "PNC", name_kr: "PNC파이낸셜", market: "US", currency: "USD", sector: "Financials" },
  { ticker: "TFC", name_kr: "트루이스트", market: "US", currency: "USD", sector: "Financials" },
  { ticker: "AIG", name_kr: "AIG", market: "US", currency: "USD", sector: "Financials" },
  { ticker: "MET", name_kr: "메트라이프", market: "US", currency: "USD", sector: "Financials" },
  { ticker: "PRU", name_kr: "푸르덴셜", market: "US", currency: "USD", sector: "Financials" },
  { ticker: "ALL", name_kr: "올스테이트", market: "US", currency: "USD", sector: "Financials" },
  { ticker: "TRV", name_kr: "트레블러스", market: "US", currency: "USD", sector: "Financials" },
  { ticker: "SPGI", name_kr: "S&P글로벌", market: "US", currency: "USD", sector: "Financials" },
  { ticker: "CME", name_kr: "CME그룹", market: "US", currency: "USD", sector: "Financials" },
  { ticker: "AMP", name_kr: "아메리프라이즈", market: "US", currency: "USD", sector: "Financials" },
  { ticker: "MS", name_kr: "모건스탠리", market: "US", currency: "USD", sector: "Financials" },
  { ticker: "PYPL", name_kr: "페이팔", market: "US", currency: "USD", sector: "Financials" },
  { ticker: "FIS", name_kr: "FIS", market: "US", currency: "USD", sector: "Financials" },
  { ticker: "FISV", name_kr: "피서브", market: "US", currency: "USD", sector: "Financials" },
  { ticker: "NEE", name_kr: "넥스트에라에너지", market: "US", currency: "USD", sector: "Utilities" },
  { ticker: "DUK", name_kr: "듀크에너지", market: "US", currency: "USD", sector: "Utilities" },
  { ticker: "SO", name_kr: "서던컴퍼니", market: "US", currency: "USD", sector: "Utilities" },
  { ticker: "AEP", name_kr: "AEP", market: "US", currency: "USD", sector: "Utilities" },
  { ticker: "D", name_kr: "도미니언에너지", market: "US", currency: "USD", sector: "Utilities" },
  { ticker: "EXC", name_kr: "엑셀론", market: "US", currency: "USD", sector: "Utilities" },
  { ticker: "PCG", name_kr: "PG&E", market: "US", currency: "USD", sector: "Utilities" },
  { ticker: "COP", name_kr: "코노코필립스", market: "US", currency: "USD", sector: "Energy" },
  { ticker: "EOG", name_kr: "EOG리소시스", market: "US", currency: "USD", sector: "Energy" },
  { ticker: "SLB", name_kr: "슐럼버거", market: "US", currency: "USD", sector: "Energy" },
  { ticker: "MPC", name_kr: "마라톤페트롤리엄", market: "US", currency: "USD", sector: "Energy" },
  { ticker: "PSX", name_kr: "필립스66", market: "US", currency: "USD", sector: "Energy" },
  { ticker: "VLO", name_kr: "발레로", market: "US", currency: "USD", sector: "Energy" },
  { ticker: "OXY", name_kr: "옥시덴탈", market: "US", currency: "USD", sector: "Energy" },
  { ticker: "PXD", name_kr: "파이오니어내추럴리소스", market: "US", currency: "USD", sector: "Energy" },
  { ticker: "FCX", name_kr: "프리포트맥모란", market: "US", currency: "USD", sector: "Materials" },
  { ticker: "NEM", name_kr: "뉴몬트", market: "US", currency: "USD", sector: "Materials" },
  { ticker: "DOW", name_kr: "다우", market: "US", currency: "USD", sector: "Materials" },
  { ticker: "DD", name_kr: "듀폰", market: "US", currency: "USD", sector: "Materials" },
  { ticker: "APD", name_kr: "에어프로덕츠", market: "US", currency: "USD", sector: "Materials" },
  { ticker: "ECL", name_kr: "에콜랩", market: "US", currency: "USD", sector: "Materials" },
  { ticker: "SHW", name_kr: "셔윈윌리엄스", market: "US", currency: "USD", sector: "Materials" },
  { ticker: "CCI", name_kr: "크라운캐슬", market: "US", currency: "USD", sector: "Real Estate" },
  { ticker: "PLD", name_kr: "프롤로지스", market: "US", currency: "USD", sector: "Real Estate" },
  { ticker: "PSA", name_kr: "퍼블릭스토리지", market: "US", currency: "USD", sector: "Real Estate" },
  { ticker: "O", name_kr: "리얼티인컴", market: "US", currency: "USD", sector: "Real Estate" },
  { ticker: "SPG", name_kr: "사이먼프로퍼티", market: "US", currency: "USD", sector: "Real Estate" },
  { ticker: "WELL", name_kr: "웰타워", market: "US", currency: "USD", sector: "Real Estate" },
  { ticker: "DHR", name_kr: "다나허", market: "US", currency: "USD", sector: "Healthcare" },
  { ticker: "TMO", name_kr: "써모피셔", market: "US", currency: "USD", sector: "Healthcare" },
  { ticker: "DXCM", name_kr: "덱스컴", market: "US", currency: "USD", sector: "Healthcare" },
  { ticker: "BSX", name_kr: "보스턴사이언티픽", market: "US", currency: "USD", sector: "Healthcare" },
  { ticker: "CI", name_kr: "시그나", market: "US", currency: "USD", sector: "Healthcare" },
  { ticker: "HUM", name_kr: "휴매나", market: "US", currency: "USD", sector: "Healthcare" },
  { ticker: "CVS", name_kr: "CVS헬스", market: "US", currency: "USD", sector: "Healthcare" },
  { ticker: "MRNA", name_kr: "모더나", market: "US", currency: "USD", sector: "Healthcare" },
  { ticker: "BIIB", name_kr: "바이오젠", market: "US", currency: "USD", sector: "Healthcare" },
  { ticker: "CL", name_kr: "콜게이트", market: "US", currency: "USD", sector: "Consumer Staples" },
  { ticker: "MDLZ", name_kr: "몬델리즈", market: "US", currency: "USD", sector: "Consumer Staples" },
  { ticker: "CHD", name_kr: "처치&드와이트", market: "US", currency: "USD", sector: "Consumer Staples" },
  { ticker: "GIS", name_kr: "제너럴밀스", market: "US", currency: "USD", sector: "Consumer Staples" },
  { ticker: "K", name_kr: "켈로그", market: "US", currency: "USD", sector: "Consumer Staples" },
  { ticker: "EL", name_kr: "에스티로더", market: "US", currency: "USD", sector: "Consumer Staples" },
  { ticker: "KMB", name_kr: "킴벌리클락", market: "US", currency: "USD", sector: "Consumer Staples" },
  { ticker: "STZ", name_kr: "컨스텔레이션브랜즈", market: "US", currency: "USD", sector: "Consumer Staples" },
  { ticker: "MNST", name_kr: "몬스터베버리지", market: "US", currency: "USD", sector: "Consumer Staples" },
  { ticker: "KHC", name_kr: "크래프트하인즈", market: "US", currency: "USD", sector: "Consumer Staples" },
  { ticker: "UPS", name_kr: "UPS", market: "US", currency: "USD", sector: "Industrials" },
  { ticker: "FDX", name_kr: "페덱스", market: "US", currency: "USD", sector: "Industrials" },
  { ticker: "LMT", name_kr: "록히드마틴", market: "US", currency: "USD", sector: "Industrials" },
  { ticker: "GD", name_kr: "제너럴다이내믹스", market: "US", currency: "USD", sector: "Industrials" },
  { ticker: "NOC", name_kr: "노스럽그러먼", market: "US", currency: "USD", sector: "Industrials" },
  { ticker: "EMR", name_kr: "에머슨", market: "US", currency: "USD", sector: "Industrials" },
  { ticker: "ETN", name_kr: "이튼", market: "US", currency: "USD", sector: "Industrials" },
  { ticker: "ITW", name_kr: "ITW", market: "US", currency: "USD", sector: "Industrials" },
  { ticker: "PH", name_kr: "파커하니핀", market: "US", currency: "USD", sector: "Industrials" },
  { ticker: "DE", name_kr: "디어&컴퍼니", market: "US", currency: "USD", sector: "Industrials" },
  { ticker: "CSX", name_kr: "CSX", market: "US", currency: "USD", sector: "Industrials" },
  { ticker: "UNP", name_kr: "유니언퍼시픽", market: "US", currency: "USD", sector: "Industrials" },
  { ticker: "NSC", name_kr: "노포크서던", market: "US", currency: "USD", sector: "Industrials" },
  { ticker: "WM", name_kr: "웨이스트매니지먼트", market: "US", currency: "USD", sector: "Industrials" },
  { ticker: "GLW", name_kr: "코닝", market: "US", currency: "USD", sector: "Technology" },
  { ticker: "ORLY", name_kr: "오라일리오토", market: "US", currency: "USD", sector: "Consumer Discretionary" },
  { ticker: "MAR", name_kr: "메리어트", market: "US", currency: "USD", sector: "Consumer Discretionary" },
  { ticker: "HLT", name_kr: "힐튼", market: "US", currency: "USD", sector: "Consumer Discretionary" },
  { ticker: "YUM", name_kr: "얌브랜즈", market: "US", currency: "USD", sector: "Consumer Discretionary" },
  { ticker: "CMG", name_kr: "치폴레", market: "US", currency: "USD", sector: "Consumer Discretionary" },
  { ticker: "TGT", name_kr: "타겟", market: "US", currency: "USD", sector: "Consumer Staples" },
  { ticker: "DG", name_kr: "달러제너럴", market: "US", currency: "USD", sector: "Consumer Staples" },
  { ticker: "ROST", name_kr: "로스스토어즈", market: "US", currency: "USD", sector: "Consumer Discretionary" },
];

// ── 한국 메가캡 후보 (KOSPI 시총 상위) ──
const KR: UniverseCandidate[] = [
  { ticker: "005930.KS", name_kr: "삼성전자", market: "KR", currency: "KRW", sector: "Technology" },
  { ticker: "000660.KS", name_kr: "SK하이닉스", market: "KR", currency: "KRW", sector: "Technology" },
  { ticker: "373220.KS", name_kr: "LG에너지솔루션", market: "KR", currency: "KRW", sector: "Industrials" },
  { ticker: "207940.KS", name_kr: "삼성바이오로직스", market: "KR", currency: "KRW", sector: "Healthcare" },
  { ticker: "005380.KS", name_kr: "현대차", market: "KR", currency: "KRW", sector: "Consumer Discretionary" },
  { ticker: "005935.KS", name_kr: "삼성전자우", market: "KR", currency: "KRW", sector: "Technology" },
  { ticker: "000270.KS", name_kr: "기아", market: "KR", currency: "KRW", sector: "Consumer Discretionary" },
  { ticker: "035420.KS", name_kr: "NAVER", market: "KR", currency: "KRW", sector: "Communication" },
  { ticker: "035720.KS", name_kr: "카카오", market: "KR", currency: "KRW", sector: "Communication" },
  { ticker: "105560.KS", name_kr: "KB금융", market: "KR", currency: "KRW", sector: "Financials" },
  { ticker: "055550.KS", name_kr: "신한지주", market: "KR", currency: "KRW", sector: "Financials" },
  { ticker: "028260.KS", name_kr: "삼성물산", market: "KR", currency: "KRW", sector: "Industrials" },
  { ticker: "068270.KS", name_kr: "셀트리온", market: "KR", currency: "KRW", sector: "Healthcare" },
  { ticker: "051910.KS", name_kr: "LG화학", market: "KR", currency: "KRW", sector: "Materials" },
  { ticker: "006400.KS", name_kr: "삼성SDI", market: "KR", currency: "KRW", sector: "Industrials" },
  { ticker: "012330.KS", name_kr: "현대모비스", market: "KR", currency: "KRW", sector: "Consumer Discretionary" },
  { ticker: "015760.KS", name_kr: "한국전력", market: "KR", currency: "KRW", sector: "Utilities" },
  { ticker: "086790.KS", name_kr: "하나금융지주", market: "KR", currency: "KRW", sector: "Financials" },
  { ticker: "003670.KS", name_kr: "포스코퓨처엠", market: "KR", currency: "KRW", sector: "Materials" },
  { ticker: "096770.KS", name_kr: "SK이노베이션", market: "KR", currency: "KRW", sector: "Energy" },
  { ticker: "009150.KS", name_kr: "삼성전기", market: "KR", currency: "KRW", sector: "Technology" },
  { ticker: "010130.KS", name_kr: "고려아연", market: "KR", currency: "KRW", sector: "Materials" },
  { ticker: "066570.KS", name_kr: "LG전자", market: "KR", currency: "KRW", sector: "Consumer Discretionary" },
  { ticker: "017670.KS", name_kr: "SK텔레콤", market: "KR", currency: "KRW", sector: "Communication" },
  { ticker: "030200.KS", name_kr: "KT", market: "KR", currency: "KRW", sector: "Communication" },
  { ticker: "032830.KS", name_kr: "삼성생명", market: "KR", currency: "KRW", sector: "Financials" },
  { ticker: "323410.KS", name_kr: "카카오뱅크", market: "KR", currency: "KRW", sector: "Financials" },
  { ticker: "316140.KS", name_kr: "우리금융지주", market: "KR", currency: "KRW", sector: "Financials" },
  { ticker: "024110.KS", name_kr: "기업은행", market: "KR", currency: "KRW", sector: "Financials" },
  { ticker: "138930.KS", name_kr: "BNK금융지주", market: "KR", currency: "KRW", sector: "Financials" },
  { ticker: "071050.KS", name_kr: "한국금융지주", market: "KR", currency: "KRW", sector: "Financials" },
  { ticker: "088980.KS", name_kr: "맥쿼리인프라", market: "KR", currency: "KRW", sector: "Financials" },
  { ticker: "316800.KS", name_kr: "삼성에피스", market: "KR", currency: "KRW", sector: "Healthcare" },
  { ticker: "068760.KS", name_kr: "셀트리온헬스케어", market: "KR", currency: "KRW", sector: "Healthcare" },
  { ticker: "302440.KS", name_kr: "SK바이오사이언스", market: "KR", currency: "KRW", sector: "Healthcare" },
  { ticker: "326030.KS", name_kr: "SK바이오팜", market: "KR", currency: "KRW", sector: "Healthcare" },
  { ticker: "196170.KS", name_kr: "알테오젠", market: "KR", currency: "KRW", sector: "Healthcare" },
  { ticker: "247540.KS", name_kr: "에코프로비엠", market: "KR", currency: "KRW", sector: "Industrials" },
  { ticker: "086520.KS", name_kr: "에코프로", market: "KR", currency: "KRW", sector: "Industrials" },
  { ticker: "066970.KS", name_kr: "엘앤에프", market: "KR", currency: "KRW", sector: "Industrials" },
  { ticker: "112610.KS", name_kr: "씨에스윈드", market: "KR", currency: "KRW", sector: "Industrials" },
  { ticker: "010140.KS", name_kr: "삼성중공업", market: "KR", currency: "KRW", sector: "Industrials" },
  { ticker: "009540.KS", name_kr: "한국조선해양", market: "KR", currency: "KRW", sector: "Industrials" },
  { ticker: "042660.KS", name_kr: "한화오션", market: "KR", currency: "KRW", sector: "Industrials" },
  { ticker: "267250.KS", name_kr: "HD현대", market: "KR", currency: "KRW", sector: "Industrials" },
  { ticker: "010950.KS", name_kr: "S-Oil", market: "KR", currency: "KRW", sector: "Energy" },
  { ticker: "267260.KS", name_kr: "HD현대일렉트릭", market: "KR", currency: "KRW", sector: "Industrials" },
  { ticker: "036570.KS", name_kr: "엔씨소프트", market: "KR", currency: "KRW", sector: "Communication" },
  { ticker: "352820.KS", name_kr: "하이브", market: "KR", currency: "KRW", sector: "Communication" },
  { ticker: "041510.KS", name_kr: "에스엠", market: "KR", currency: "KRW", sector: "Communication" },
  { ticker: "035900.KS", name_kr: "JYP엔터", market: "KR", currency: "KRW", sector: "Communication" },
  { ticker: "036460.KS", name_kr: "한국가스공사", market: "KR", currency: "KRW", sector: "Utilities" },
  { ticker: "047040.KS", name_kr: "대우건설", market: "KR", currency: "KRW", sector: "Industrials" },
  { ticker: "000720.KS", name_kr: "현대건설", market: "KR", currency: "KRW", sector: "Industrials" },
  { ticker: "005490.KS", name_kr: "POSCO홀딩스", market: "KR", currency: "KRW", sector: "Materials" },
  { ticker: "010520.KS", name_kr: "현대차2우B", market: "KR", currency: "KRW", sector: "Consumer Discretionary" },
  { ticker: "011170.KS", name_kr: "롯데케미칼", market: "KR", currency: "KRW", sector: "Materials" },
  { ticker: "004020.KS", name_kr: "현대제철", market: "KR", currency: "KRW", sector: "Materials" },
  { ticker: "001040.KS", name_kr: "CJ", market: "KR", currency: "KRW", sector: "Industrials" },
  { ticker: "097950.KS", name_kr: "CJ제일제당", market: "KR", currency: "KRW", sector: "Consumer Staples" },
  { ticker: "271560.KS", name_kr: "오리온", market: "KR", currency: "KRW", sector: "Consumer Staples" },
  { ticker: "004990.KS", name_kr: "롯데지주", market: "KR", currency: "KRW", sector: "Industrials" },
  { ticker: "008770.KS", name_kr: "호텔신라", market: "KR", currency: "KRW", sector: "Consumer Discretionary" },
  { ticker: "029780.KS", name_kr: "삼성카드", market: "KR", currency: "KRW", sector: "Financials" },
  { ticker: "139480.KS", name_kr: "이마트", market: "KR", currency: "KRW", sector: "Consumer Staples" },
  { ticker: "069960.KS", name_kr: "현대백화점", market: "KR", currency: "KRW", sector: "Consumer Discretionary" },
  { ticker: "023530.KS", name_kr: "롯데쇼핑", market: "KR", currency: "KRW", sector: "Consumer Discretionary" },
  { ticker: "021240.KS", name_kr: "코웨이", market: "KR", currency: "KRW", sector: "Consumer Discretionary" },
  { ticker: "192820.KS", name_kr: "코스맥스", market: "KR", currency: "KRW", sector: "Consumer Staples" },
  { ticker: "090430.KS", name_kr: "아모레퍼시픽", market: "KR", currency: "KRW", sector: "Consumer Staples" },
  { ticker: "051900.KS", name_kr: "LG생활건강", market: "KR", currency: "KRW", sector: "Consumer Staples" },
  { ticker: "032640.KS", name_kr: "LG유플러스", market: "KR", currency: "KRW", sector: "Communication" },
  { ticker: "003550.KS", name_kr: "LG", market: "KR", currency: "KRW", sector: "Industrials" },
  { ticker: "034730.KS", name_kr: "SK", market: "KR", currency: "KRW", sector: "Industrials" },
  { ticker: "003490.KS", name_kr: "대한항공", market: "KR", currency: "KRW", sector: "Industrials" },
  { ticker: "020560.KS", name_kr: "아시아나항공", market: "KR", currency: "KRW", sector: "Industrials" },
  { ticker: "047810.KS", name_kr: "한국항공우주", market: "KR", currency: "KRW", sector: "Industrials" },
  { ticker: "012450.KS", name_kr: "한화에어로스페이스", market: "KR", currency: "KRW", sector: "Industrials" },
  { ticker: "272210.KS", name_kr: "한화시스템", market: "KR", currency: "KRW", sector: "Industrials" },
  { ticker: "079550.KS", name_kr: "LIG넥스원", market: "KR", currency: "KRW", sector: "Industrials" },
  { ticker: "064350.KS", name_kr: "현대로템", market: "KR", currency: "KRW", sector: "Industrials" },
  { ticker: "086280.KS", name_kr: "현대글로비스", market: "KR", currency: "KRW", sector: "Industrials" },
  { ticker: "035250.KS", name_kr: "강원랜드", market: "KR", currency: "KRW", sector: "Consumer Discretionary" },
  { ticker: "078930.KS", name_kr: "GS", market: "KR", currency: "KRW", sector: "Industrials" },
  { ticker: "180640.KS", name_kr: "한진칼", market: "KR", currency: "KRW", sector: "Industrials" },
  { ticker: "108670.KS", name_kr: "LG디스플레이", market: "KR", currency: "KRW", sector: "Technology" },
  { ticker: "034220.KS", name_kr: "LG디스플레이(우)", market: "KR", currency: "KRW", sector: "Technology" },
  { ticker: "402340.KS", name_kr: "SK스퀘어", market: "KR", currency: "KRW", sector: "Communication" },
  { ticker: "353200.KS", name_kr: "대덕전자", market: "KR", currency: "KRW", sector: "Technology" },
  { ticker: "418550.KS", name_kr: "제이오", market: "KR", currency: "KRW", sector: "Industrials" },
  { ticker: "267290.KS", name_kr: "경동도시가스", market: "KR", currency: "KRW", sector: "Utilities" },
  { ticker: "377300.KS", name_kr: "카카오페이", market: "KR", currency: "KRW", sector: "Financials" },
  { ticker: "263750.KS", name_kr: "펄어비스", market: "KR", currency: "KRW", sector: "Communication" },
  { ticker: "251270.KS", name_kr: "넷마블", market: "KR", currency: "KRW", sector: "Communication" },
  { ticker: "112040.KS", name_kr: "위메이드", market: "KR", currency: "KRW", sector: "Communication" },
  { ticker: "079160.KS", name_kr: "CJ CGV", market: "KR", currency: "KRW", sector: "Communication" },
];

// ── 일본 메가캡 후보 ──
const JP: UniverseCandidate[] = [
  { ticker: "7203.T", name_kr: "토요타", market: "JP", currency: "JPY", sector: "Consumer Discretionary" },
  { ticker: "6758.T", name_kr: "소니", market: "JP", currency: "JPY", sector: "Technology" },
  { ticker: "6861.T", name_kr: "키엔스", market: "JP", currency: "JPY", sector: "Industrials" },
  { ticker: "8306.T", name_kr: "미쓰비시UFJ", market: "JP", currency: "JPY", sector: "Financials" },
  { ticker: "9984.T", name_kr: "소프트뱅크그룹", market: "JP", currency: "JPY", sector: "Communication" },
  { ticker: "9983.T", name_kr: "패스트리테일링", market: "JP", currency: "JPY", sector: "Consumer Discretionary" },
  { ticker: "8035.T", name_kr: "도쿄일렉트론", market: "JP", currency: "JPY", sector: "Technology" },
  { ticker: "7974.T", name_kr: "닌텐도", market: "JP", currency: "JPY", sector: "Communication" },
  { ticker: "4063.T", name_kr: "신에츠화학", market: "JP", currency: "JPY", sector: "Materials" },
  { ticker: "6098.T", name_kr: "리쿠르트", market: "JP", currency: "JPY", sector: "Industrials" },
  { ticker: "6501.T", name_kr: "히타치", market: "JP", currency: "JPY", sector: "Industrials" },
  { ticker: "8316.T", name_kr: "미쓰이스미토모금융", market: "JP", currency: "JPY", sector: "Financials" },
  { ticker: "8058.T", name_kr: "미쓰비시상사", market: "JP", currency: "JPY", sector: "Industrials" },
  { ticker: "7267.T", name_kr: "혼다", market: "JP", currency: "JPY", sector: "Consumer Discretionary" },
  { ticker: "8001.T", name_kr: "이토추상사", market: "JP", currency: "JPY", sector: "Industrials" },
  { ticker: "8031.T", name_kr: "미쓰이물산", market: "JP", currency: "JPY", sector: "Industrials" },
  { ticker: "9433.T", name_kr: "KDDI", market: "JP", currency: "JPY", sector: "Communication" },
  { ticker: "4502.T", name_kr: "다케다제약", market: "JP", currency: "JPY", sector: "Healthcare" },
  { ticker: "6902.T", name_kr: "덴소", market: "JP", currency: "JPY", sector: "Consumer Discretionary" },
  { ticker: "8411.T", name_kr: "미즈호금융", market: "JP", currency: "JPY", sector: "Financials" },
  { ticker: "7011.T", name_kr: "미쓰비시중공업", market: "JP", currency: "JPY", sector: "Industrials" },
  { ticker: "7741.T", name_kr: "호야", market: "JP", currency: "JPY", sector: "Healthcare" },
  { ticker: "4661.T", name_kr: "오리엔탈랜드", market: "JP", currency: "JPY", sector: "Consumer Discretionary" },
  { ticker: "9432.T", name_kr: "NTT", market: "JP", currency: "JPY", sector: "Communication" },
  { ticker: "6594.T", name_kr: "니덱", market: "JP", currency: "JPY", sector: "Industrials" },
  { ticker: "9433.T", name_kr: "KDDI", market: "JP", currency: "JPY", sector: "Communication" },
  { ticker: "6920.T", name_kr: "레이저텍", market: "JP", currency: "JPY", sector: "Technology" },
  { ticker: "4543.T", name_kr: "테루모", market: "JP", currency: "JPY", sector: "Healthcare" },
  { ticker: "4523.T", name_kr: "에자이", market: "JP", currency: "JPY", sector: "Healthcare" },
  { ticker: "4519.T", name_kr: "주가이제약", market: "JP", currency: "JPY", sector: "Healthcare" },
  { ticker: "4568.T", name_kr: "다이이치산쿄", market: "JP", currency: "JPY", sector: "Healthcare" },
  { ticker: "4503.T", name_kr: "아스텔라스제약", market: "JP", currency: "JPY", sector: "Healthcare" },
  { ticker: "4578.T", name_kr: "오츠카홀딩스", market: "JP", currency: "JPY", sector: "Healthcare" },
  { ticker: "6273.T", name_kr: "SMC", market: "JP", currency: "JPY", sector: "Industrials" },
  { ticker: "6367.T", name_kr: "다이킨공업", market: "JP", currency: "JPY", sector: "Industrials" },
  { ticker: "6326.T", name_kr: "쿠보타", market: "JP", currency: "JPY", sector: "Industrials" },
  { ticker: "6981.T", name_kr: "무라타제작소", market: "JP", currency: "JPY", sector: "Technology" },
  { ticker: "6952.T", name_kr: "카시오", market: "JP", currency: "JPY", sector: "Consumer Discretionary" },
  { ticker: "6701.T", name_kr: "NEC", market: "JP", currency: "JPY", sector: "Technology" },
  { ticker: "6724.T", name_kr: "세이코엡손", market: "JP", currency: "JPY", sector: "Technology" },
  { ticker: "6752.T", name_kr: "파나소닉", market: "JP", currency: "JPY", sector: "Consumer Discretionary" },
  { ticker: "6976.T", name_kr: "타이요유전", market: "JP", currency: "JPY", sector: "Technology" },
  { ticker: "6845.T", name_kr: "아즈빌", market: "JP", currency: "JPY", sector: "Industrials" },
  { ticker: "6273.T", name_kr: "SMC", market: "JP", currency: "JPY", sector: "Industrials" },
  { ticker: "6273.T", name_kr: "SMC", market: "JP", currency: "JPY", sector: "Industrials" },
  { ticker: "7261.T", name_kr: "마쓰다", market: "JP", currency: "JPY", sector: "Consumer Discretionary" },
  { ticker: "7269.T", name_kr: "스즈키", market: "JP", currency: "JPY", sector: "Consumer Discretionary" },
  { ticker: "7270.T", name_kr: "스바루", market: "JP", currency: "JPY", sector: "Consumer Discretionary" },
  { ticker: "7259.T", name_kr: "아이신", market: "JP", currency: "JPY", sector: "Consumer Discretionary" },
  { ticker: "7751.T", name_kr: "캐논", market: "JP", currency: "JPY", sector: "Technology" },
  { ticker: "7733.T", name_kr: "올림푸스", market: "JP", currency: "JPY", sector: "Healthcare" },
  { ticker: "8053.T", name_kr: "스미토모상사", market: "JP", currency: "JPY", sector: "Industrials" },
  { ticker: "8002.T", name_kr: "마루베니", market: "JP", currency: "JPY", sector: "Industrials" },
  { ticker: "9020.T", name_kr: "JR동일본", market: "JP", currency: "JPY", sector: "Industrials" },
  { ticker: "9022.T", name_kr: "JR도카이", market: "JP", currency: "JPY", sector: "Industrials" },
  { ticker: "9201.T", name_kr: "JAL", market: "JP", currency: "JPY", sector: "Industrials" },
  { ticker: "9202.T", name_kr: "ANA홀딩스", market: "JP", currency: "JPY", sector: "Industrials" },
  { ticker: "9101.T", name_kr: "일본우편선", market: "JP", currency: "JPY", sector: "Industrials" },
  { ticker: "9104.T", name_kr: "상선미쓰이", market: "JP", currency: "JPY", sector: "Industrials" },
  { ticker: "9531.T", name_kr: "도쿄가스", market: "JP", currency: "JPY", sector: "Utilities" },
  { ticker: "9501.T", name_kr: "도쿄전력", market: "JP", currency: "JPY", sector: "Utilities" },
  { ticker: "5108.T", name_kr: "브리지스톤", market: "JP", currency: "JPY", sector: "Consumer Discretionary" },
  { ticker: "5401.T", name_kr: "일본제철", market: "JP", currency: "JPY", sector: "Materials" },
  { ticker: "5713.T", name_kr: "스미토모금속광산", market: "JP", currency: "JPY", sector: "Materials" },
  { ticker: "5020.T", name_kr: "ENEOS홀딩스", market: "JP", currency: "JPY", sector: "Energy" },
  { ticker: "1605.T", name_kr: "INPEX", market: "JP", currency: "JPY", sector: "Energy" },
  { ticker: "2914.T", name_kr: "JT", market: "JP", currency: "JPY", sector: "Consumer Staples" },
  { ticker: "2502.T", name_kr: "아사히그룹", market: "JP", currency: "JPY", sector: "Consumer Staples" },
  { ticker: "2503.T", name_kr: "기린홀딩스", market: "JP", currency: "JPY", sector: "Consumer Staples" },
  { ticker: "2802.T", name_kr: "아지노모토", market: "JP", currency: "JPY", sector: "Consumer Staples" },
  { ticker: "4452.T", name_kr: "카오", market: "JP", currency: "JPY", sector: "Consumer Staples" },
  { ticker: "4911.T", name_kr: "시세이도", market: "JP", currency: "JPY", sector: "Consumer Staples" },
  { ticker: "3382.T", name_kr: "세븐&아이", market: "JP", currency: "JPY", sector: "Consumer Staples" },
  { ticker: "3086.T", name_kr: "J.프론트리테일링", market: "JP", currency: "JPY", sector: "Consumer Discretionary" },
  { ticker: "3099.T", name_kr: "미쓰코시이세탄", market: "JP", currency: "JPY", sector: "Consumer Discretionary" },
  { ticker: "8267.T", name_kr: "이온", market: "JP", currency: "JPY", sector: "Consumer Staples" },
  { ticker: "9021.T", name_kr: "JR서일본", market: "JP", currency: "JPY", sector: "Industrials" },
  { ticker: "9613.T", name_kr: "NTT데이터", market: "JP", currency: "JPY", sector: "Technology" },
  { ticker: "4684.T", name_kr: "오빅", market: "JP", currency: "JPY", sector: "Technology" },
  { ticker: "4307.T", name_kr: "노무라연구소", market: "JP", currency: "JPY", sector: "Technology" },
  { ticker: "9697.T", name_kr: "캡콤", market: "JP", currency: "JPY", sector: "Communication" },
  { ticker: "9684.T", name_kr: "스퀘어에닉스", market: "JP", currency: "JPY", sector: "Communication" },
  { ticker: "9766.T", name_kr: "코나미", market: "JP", currency: "JPY", sector: "Communication" },
  { ticker: "7832.T", name_kr: "반다이남코", market: "JP", currency: "JPY", sector: "Communication" },
  { ticker: "4324.T", name_kr: "덴츠", market: "JP", currency: "JPY", sector: "Communication" },
  { ticker: "2413.T", name_kr: "엠쓰리", market: "JP", currency: "JPY", sector: "Healthcare" },
  { ticker: "2371.T", name_kr: "카카쿠닷컴", market: "JP", currency: "JPY", sector: "Communication" },
  { ticker: "4385.T", name_kr: "메르카리", market: "JP", currency: "JPY", sector: "Consumer Discretionary" },
  { ticker: "3659.T", name_kr: "넥슨", market: "JP", currency: "JPY", sector: "Communication" },
  { ticker: "4755.T", name_kr: "라쿠텐", market: "JP", currency: "JPY", sector: "Consumer Discretionary" },
  { ticker: "9434.T", name_kr: "소프트뱅크(통신)", market: "JP", currency: "JPY", sector: "Communication" },
  { ticker: "4661.T", name_kr: "오리엔탈랜드", market: "JP", currency: "JPY", sector: "Consumer Discretionary" },
  { ticker: "8801.T", name_kr: "미쓰이부동산", market: "JP", currency: "JPY", sector: "Real Estate" },
  { ticker: "8802.T", name_kr: "미쓰비시지소", market: "JP", currency: "JPY", sector: "Real Estate" },
  { ticker: "3289.T", name_kr: "도큐부동산", market: "JP", currency: "JPY", sector: "Real Estate" },
  { ticker: "4612.T", name_kr: "닛폰페인트", market: "JP", currency: "JPY", sector: "Materials" },
  { ticker: "4188.T", name_kr: "미쓰비시화학", market: "JP", currency: "JPY", sector: "Materials" },
  { ticker: "4042.T", name_kr: "도소", market: "JP", currency: "JPY", sector: "Materials" },
  { ticker: "5108.T", name_kr: "브리지스톤", market: "JP", currency: "JPY", sector: "Consumer Discretionary" },
];

// ── 중국 메가캡 후보 (본토 A주 + 홍콩 H주) ──
const CN: UniverseCandidate[] = [
  { ticker: "0700.HK", name_kr: "텐센트", market: "CN", currency: "HKD", sector: "Communication" },
  { ticker: "9988.HK", name_kr: "알리바바(HK)", market: "CN", currency: "HKD", sector: "Consumer Discretionary" },
  { ticker: "1810.HK", name_kr: "샤오미", market: "CN", currency: "HKD", sector: "Technology" },
  { ticker: "9618.HK", name_kr: "JD닷컴", market: "CN", currency: "HKD", sector: "Consumer Discretionary" },
  { ticker: "3690.HK", name_kr: "메이투안", market: "CN", currency: "HKD", sector: "Consumer Discretionary" },
  { ticker: "0941.HK", name_kr: "차이나모바일", market: "CN", currency: "HKD", sector: "Communication" },
  { ticker: "1398.HK", name_kr: "공상은행", market: "CN", currency: "HKD", sector: "Financials" },
  { ticker: "0939.HK", name_kr: "건설은행", market: "CN", currency: "HKD", sector: "Financials" },
  { ticker: "2318.HK", name_kr: "핑안보험(HK)", market: "CN", currency: "HKD", sector: "Financials" },
  { ticker: "600519.SS", name_kr: "귀주모태", market: "CN", currency: "CNY", sector: "Consumer Staples" },
  { ticker: "601318.SS", name_kr: "핑안보험(A)", market: "CN", currency: "CNY", sector: "Financials" },
  { ticker: "600036.SS", name_kr: "초상은행", market: "CN", currency: "CNY", sector: "Financials" },
  { ticker: "000333.SZ", name_kr: "메이디그룹", market: "CN", currency: "CNY", sector: "Consumer Discretionary" },
  { ticker: "000858.SZ", name_kr: "오량액", market: "CN", currency: "CNY", sector: "Consumer Staples" },
  { ticker: "002594.SZ", name_kr: "BYD", market: "CN", currency: "CNY", sector: "Consumer Discretionary" },
  { ticker: "300750.SZ", name_kr: "CATL", market: "CN", currency: "CNY", sector: "Industrials" },
  { ticker: "600276.SS", name_kr: "장쑤헝루이의약", market: "CN", currency: "CNY", sector: "Healthcare" },
  { ticker: "600900.SS", name_kr: "양쯔강전력", market: "CN", currency: "CNY", sector: "Utilities" },
  { ticker: "002475.SZ", name_kr: "리쉰정밀", market: "CN", currency: "CNY", sector: "Technology" },
  { ticker: "601888.SS", name_kr: "중국국제여행", market: "CN", currency: "CNY", sector: "Consumer Discretionary" },
  { ticker: "601628.SS", name_kr: "중국인수보험", market: "CN", currency: "CNY", sector: "Financials" },
  { ticker: "601988.SS", name_kr: "중국은행", market: "CN", currency: "CNY", sector: "Financials" },
  { ticker: "601398.SS", name_kr: "중국공상은행(A)", market: "CN", currency: "CNY", sector: "Financials" },
  { ticker: "601939.SS", name_kr: "건설은행(A)", market: "CN", currency: "CNY", sector: "Financials" },
  { ticker: "601288.SS", name_kr: "농업은행", market: "CN", currency: "CNY", sector: "Financials" },
  { ticker: "601166.SS", name_kr: "흥업은행", market: "CN", currency: "CNY", sector: "Financials" },
  { ticker: "600000.SS", name_kr: "푸둥발전은행", market: "CN", currency: "CNY", sector: "Financials" },
  { ticker: "600030.SS", name_kr: "중신증권", market: "CN", currency: "CNY", sector: "Financials" },
  { ticker: "601881.SS", name_kr: "중국은하증권", market: "CN", currency: "CNY", sector: "Financials" },
  { ticker: "601788.SS", name_kr: "광다증권", market: "CN", currency: "CNY", sector: "Financials" },
  { ticker: "600837.SS", name_kr: "해통증권", market: "CN", currency: "CNY", sector: "Financials" },
  { ticker: "601985.SS", name_kr: "중국핵전", market: "CN", currency: "CNY", sector: "Utilities" },
  { ticker: "600028.SS", name_kr: "중국석유화공", market: "CN", currency: "CNY", sector: "Energy" },
  { ticker: "601857.SS", name_kr: "페트로차이나", market: "CN", currency: "CNY", sector: "Energy" },
  { ticker: "0857.HK", name_kr: "페트로차이나(HK)", market: "CN", currency: "HKD", sector: "Energy" },
  { ticker: "0386.HK", name_kr: "시노펙(HK)", market: "CN", currency: "HKD", sector: "Energy" },
  { ticker: "1088.HK", name_kr: "차이나선화에너지", market: "CN", currency: "HKD", sector: "Energy" },
  { ticker: "0883.HK", name_kr: "CNOOC", market: "CN", currency: "HKD", sector: "Energy" },
  { ticker: "1024.HK", name_kr: "콰이쇼우", market: "CN", currency: "HKD", sector: "Communication" },
  { ticker: "9999.HK", name_kr: "넷이즈", market: "CN", currency: "HKD", sector: "Communication" },
  { ticker: "2628.HK", name_kr: "차이나라이프", market: "CN", currency: "HKD", sector: "Financials" },
  { ticker: "1299.HK", name_kr: "AIA그룹", market: "CN", currency: "HKD", sector: "Financials" },
  { ticker: "0005.HK", name_kr: "HSBC홀딩스(HK)", market: "CN", currency: "HKD", sector: "Financials" },
  { ticker: "1109.HK", name_kr: "차이나리소시스랜드", market: "CN", currency: "HKD", sector: "Real Estate" },
  { ticker: "1113.HK", name_kr: "CK허치슨", market: "CN", currency: "HKD", sector: "Industrials" },
  { ticker: "0883.HK", name_kr: "CNOOC", market: "CN", currency: "HKD", sector: "Energy" },
  { ticker: "0027.HK", name_kr: "갤럭시엔터테인먼트", market: "CN", currency: "HKD", sector: "Consumer Discretionary" },
  { ticker: "1928.HK", name_kr: "샌즈차이나", market: "CN", currency: "HKD", sector: "Consumer Discretionary" },
  { ticker: "0388.HK", name_kr: "홍콩거래소", market: "CN", currency: "HKD", sector: "Financials" },
  { ticker: "0011.HK", name_kr: "항생은행", market: "CN", currency: "HKD", sector: "Financials" },
  { ticker: "0002.HK", name_kr: "CLP홀딩스", market: "CN", currency: "HKD", sector: "Utilities" },
  { ticker: "0066.HK", name_kr: "MTR", market: "CN", currency: "HKD", sector: "Industrials" },
  { ticker: "1972.HK", name_kr: "스와이어퍼시픽", market: "CN", currency: "HKD", sector: "Real Estate" },
  { ticker: "0004.HK", name_kr: "와프그룹", market: "CN", currency: "HKD", sector: "Real Estate" },
  { ticker: "0017.HK", name_kr: "뉴월드디벨롭먼트", market: "CN", currency: "HKD", sector: "Real Estate" },
  { ticker: "0016.HK", name_kr: "선홍카이프로퍼티", market: "CN", currency: "HKD", sector: "Real Estate" },
  { ticker: "0823.HK", name_kr: "링크리츠", market: "CN", currency: "HKD", sector: "Real Estate" },
  { ticker: "1093.HK", name_kr: "CSPC제약", market: "CN", currency: "HKD", sector: "Healthcare" },
  { ticker: "1177.HK", name_kr: "선전메디컬", market: "CN", currency: "HKD", sector: "Healthcare" },
  { ticker: "2382.HK", name_kr: "선테크옵토일렉트로닉", market: "CN", currency: "HKD", sector: "Technology" },
  { ticker: "0992.HK", name_kr: "레노버", market: "CN", currency: "HKD", sector: "Technology" },
  { ticker: "1810.HK", name_kr: "샤오미", market: "CN", currency: "HKD", sector: "Technology" },
  { ticker: "002230.SZ", name_kr: "아이플라이텍", market: "CN", currency: "CNY", sector: "Technology" },
  { ticker: "002415.SZ", name_kr: "하이크비전", market: "CN", currency: "CNY", sector: "Technology" },
  { ticker: "300059.SZ", name_kr: "동방재부", market: "CN", currency: "CNY", sector: "Financials" },
  { ticker: "300760.SZ", name_kr: "마인드레이", market: "CN", currency: "CNY", sector: "Healthcare" },
  { ticker: "300122.SZ", name_kr: "지이파마", market: "CN", currency: "CNY", sector: "Healthcare" },
];

// ── 유럽 메가캡 후보 ──
const EU: UniverseCandidate[] = [
  { ticker: "ASML", name_kr: "ASML", market: "EU", currency: "USD", sector: "Technology" }, // ADR 달러
  { ticker: "MC.PA", name_kr: "LVMH", market: "EU", currency: "EUR", sector: "Consumer Discretionary" },
  { ticker: "NVO", name_kr: "노보노디스크", market: "EU", currency: "USD", sector: "Healthcare" },
  { ticker: "SAP", name_kr: "SAP", market: "EU", currency: "USD", sector: "Technology" },
  { ticker: "NESN.SW", name_kr: "네슬레", market: "EU", currency: "EUR", sector: "Consumer Staples" },
  { ticker: "SHEL", name_kr: "쉘", market: "EU", currency: "USD", sector: "Energy" },
  { ticker: "AZN", name_kr: "아스트라제네카", market: "EU", currency: "USD", sector: "Healthcare" },
  { ticker: "TTE", name_kr: "토탈에너지", market: "EU", currency: "USD", sector: "Energy" },
  { ticker: "RY.PA", name_kr: "에르메스", market: "EU", currency: "EUR", sector: "Consumer Discretionary" },
  { ticker: "OR.PA", name_kr: "로레알", market: "EU", currency: "EUR", sector: "Consumer Staples" },
  { ticker: "SIE.DE", name_kr: "지멘스", market: "EU", currency: "EUR", sector: "Industrials" },
  { ticker: "ULVR.L", name_kr: "유니레버", market: "EU", currency: "GBP", sector: "Consumer Staples" },
  { ticker: "ROG.SW", name_kr: "로슈", market: "EU", currency: "EUR", sector: "Healthcare" },
  { ticker: "SAN.PA", name_kr: "사노피", market: "EU", currency: "EUR", sector: "Healthcare" },
  { ticker: "NOVN.SW", name_kr: "노바티스", market: "EU", currency: "EUR", sector: "Healthcare" },
  { ticker: "ZURN.SW", name_kr: "취리히보험", market: "EU", currency: "EUR", sector: "Financials" },
  { ticker: "CSGN.SW", name_kr: "크레디트스위스(폐지)", market: "EU", currency: "EUR", sector: "Financials" },
  { ticker: "UBSG.SW", name_kr: "UBS", market: "EU", currency: "EUR", sector: "Financials" },
  { ticker: "ABBN.SW", name_kr: "ABB", market: "EU", currency: "EUR", sector: "Industrials" },
  { ticker: "GIVN.SW", name_kr: "지바우단", market: "EU", currency: "EUR", sector: "Materials" },
  { ticker: "AIR.PA", name_kr: "에어버스", market: "EU", currency: "EUR", sector: "Industrials" },
  { ticker: "SAN.MC", name_kr: "산탄데르", market: "EU", currency: "EUR", sector: "Financials" },
  { ticker: "ITX.MC", name_kr: "인디텍스", market: "EU", currency: "EUR", sector: "Consumer Discretionary" },
  { ticker: "BBVA.MC", name_kr: "BBVA", market: "EU", currency: "EUR", sector: "Financials" },
  { ticker: "IBE.MC", name_kr: "이베르드롤라", market: "EU", currency: "EUR", sector: "Utilities" },
  { ticker: "BNP.PA", name_kr: "BNP파리바", market: "EU", currency: "EUR", sector: "Financials" },
  { ticker: "GLE.PA", name_kr: "소시에테제네랄", market: "EU", currency: "EUR", sector: "Financials" },
  { ticker: "CS.PA", name_kr: "악사", market: "EU", currency: "EUR", sector: "Financials" },
  { ticker: "DG.PA", name_kr: "비올리아", market: "EU", currency: "EUR", sector: "Utilities" },
  { ticker: "DTE.DE", name_kr: "도이체텔레콤", market: "EU", currency: "EUR", sector: "Communication" },
  { ticker: "ALV.DE", name_kr: "알리안츠", market: "EU", currency: "EUR", sector: "Financials" },
  { ticker: "MUV2.DE", name_kr: "뮌헨재보험", market: "EU", currency: "EUR", sector: "Financials" },
  { ticker: "BMW.DE", name_kr: "BMW", market: "EU", currency: "EUR", sector: "Consumer Discretionary" },
  { ticker: "VOW3.DE", name_kr: "폭스바겐", market: "EU", currency: "EUR", sector: "Consumer Discretionary" },
  { ticker: "DBK.DE", name_kr: "도이체방크", market: "EU", currency: "EUR", sector: "Financials" },
  { ticker: "DHL.DE", name_kr: "도이체포스트", market: "EU", currency: "EUR", sector: "Industrials" },
  { ticker: "HEN3.DE", name_kr: "헨켈", market: "EU", currency: "EUR", sector: "Consumer Staples" },
  { ticker: "BAS.DE", name_kr: "BASF", market: "EU", currency: "EUR", sector: "Materials" },
  { ticker: "RWE.DE", name_kr: "RWE", market: "EU", currency: "EUR", sector: "Utilities" },
  { ticker: "EOAN.DE", name_kr: "E.ON", market: "EU", currency: "EUR", sector: "Utilities" },
  { ticker: "VOD.L", name_kr: "보다폰", market: "EU", currency: "GBP", sector: "Communication" },
  { ticker: "BP.L", name_kr: "BP", market: "EU", currency: "GBP", sector: "Energy" },
  { ticker: "LLOY.L", name_kr: "로이즈은행", market: "EU", currency: "GBP", sector: "Financials" },
  { ticker: "BARC.L", name_kr: "바클레이즈", market: "EU", currency: "GBP", sector: "Financials" },
  { ticker: "GSK.L", name_kr: "GSK", market: "EU", currency: "GBP", sector: "Healthcare" },
  { ticker: "RIO.L", name_kr: "리오틴토", market: "EU", currency: "GBP", sector: "Materials" },
  { ticker: "BHP.L", name_kr: "BHP", market: "EU", currency: "GBP", sector: "Materials" },
  { ticker: "DGE.L", name_kr: "디아지오", market: "EU", currency: "GBP", sector: "Consumer Staples" },
  { ticker: "REL.L", name_kr: "렐엑스", market: "EU", currency: "GBP", sector: "Communication" },
  { ticker: "BATS.L", name_kr: "BAT", market: "EU", currency: "GBP", sector: "Consumer Staples" },
  { ticker: "STAN.L", name_kr: "스탠다드차타드", market: "EU", currency: "GBP", sector: "Financials" },
  { ticker: "INGA.AS", name_kr: "ING", market: "EU", currency: "EUR", sector: "Financials" },
  { ticker: "MT.AS", name_kr: "아르셀로미탈", market: "EU", currency: "EUR", sector: "Materials" },
  { ticker: "PHIA.AS", name_kr: "필립스", market: "EU", currency: "EUR", sector: "Healthcare" },
  { ticker: "ENI.MI", name_kr: "에니", market: "EU", currency: "EUR", sector: "Energy" },
  { ticker: "ENEL.MI", name_kr: "에넬", market: "EU", currency: "EUR", sector: "Utilities" },
  { ticker: "ISP.MI", name_kr: "인테사산파올로", market: "EU", currency: "EUR", sector: "Financials" },
  { ticker: "STLA.MI", name_kr: "스텔란티스", market: "EU", currency: "EUR", sector: "Consumer Discretionary" },
  { ticker: "EQNR.OL", name_kr: "에퀴노르", market: "EU", currency: "EUR", sector: "Energy" },
  { ticker: "ATCO-A.ST", name_kr: "아틀라스콥코", market: "EU", currency: "EUR", sector: "Industrials" },
  { ticker: "INVE-B.ST", name_kr: "인베스토", market: "EU", currency: "EUR", sector: "Financials" },
  { ticker: "VOLV-B.ST", name_kr: "볼보", market: "EU", currency: "EUR", sector: "Industrials" },
  { ticker: "MAERSK-B.CO", name_kr: "머스크", market: "EU", currency: "EUR", sector: "Industrials" },
  { ticker: "DSV.CO", name_kr: "DSV", market: "EU", currency: "EUR", sector: "Industrials" },
  { ticker: "SHEL.L", name_kr: "쉘(런던)", market: "EU", currency: "GBP", sector: "Energy" },
];

// ── 기타 (대만/인도/브라질) ──
const OTHER: UniverseCandidate[] = [
  { ticker: "TSM", name_kr: "TSMC(ADR)", market: "OTHER", currency: "USD", sector: "Technology" },
  { ticker: "2317.TW", name_kr: "혼하이정밀", market: "OTHER", currency: "TWD", sector: "Technology" },
  { ticker: "2454.TW", name_kr: "미디어텍", market: "OTHER", currency: "TWD", sector: "Technology" },
  { ticker: "TCS.NS", name_kr: "TCS(인도)", market: "OTHER", currency: "INR", sector: "Technology" },
  { ticker: "RELIANCE.NS", name_kr: "릴라이언스", market: "OTHER", currency: "INR", sector: "Energy" },
  { ticker: "HDFCBANK.NS", name_kr: "HDFC은행", market: "OTHER", currency: "INR", sector: "Financials" },
  { ticker: "INFY", name_kr: "인포시스(ADR)", market: "OTHER", currency: "USD", sector: "Technology" },
  { ticker: "ITUB", name_kr: "이타우은행(ADR)", market: "OTHER", currency: "USD", sector: "Financials" },
  { ticker: "VALE", name_kr: "발레(ADR)", market: "OTHER", currency: "USD", sector: "Materials" },
  { ticker: "BABA", name_kr: "알리바바(ADR)", market: "OTHER", currency: "USD", sector: "Consumer Discretionary" },
  { ticker: "PDD", name_kr: "핀둬둬(ADR)", market: "OTHER", currency: "USD", sector: "Consumer Discretionary" },
  { ticker: "NIO", name_kr: "니오(ADR)", market: "OTHER", currency: "USD", sector: "Consumer Discretionary" },
  { ticker: "BIDU", name_kr: "바이두(ADR)", market: "OTHER", currency: "USD", sector: "Communication" },
  { ticker: "JD", name_kr: "JD(ADR)", market: "OTHER", currency: "USD", sector: "Consumer Discretionary" },
  { ticker: "BILI", name_kr: "비리비리", market: "OTHER", currency: "USD", sector: "Communication" },
  { ticker: "TCEHY", name_kr: "텐센트(ADR)", market: "OTHER", currency: "USD", sector: "Communication" },
  { ticker: "2308.TW", name_kr: "델타일렉트로닉스", market: "OTHER", currency: "TWD", sector: "Technology" },
  { ticker: "2412.TW", name_kr: "중화전신", market: "OTHER", currency: "TWD", sector: "Communication" },
  { ticker: "2882.TW", name_kr: "캐세이금융", market: "OTHER", currency: "TWD", sector: "Financials" },
  { ticker: "2891.TW", name_kr: "중신금융", market: "OTHER", currency: "TWD", sector: "Financials" },
  { ticker: "2881.TW", name_kr: "푸방금융", market: "OTHER", currency: "TWD", sector: "Financials" },
  { ticker: "1301.TW", name_kr: "포모사플라스틱", market: "OTHER", currency: "TWD", sector: "Materials" },
  { ticker: "1303.TW", name_kr: "난야플라스틱", market: "OTHER", currency: "TWD", sector: "Materials" },
  { ticker: "BHARTIARTL.NS", name_kr: "바티에어텔", market: "OTHER", currency: "INR", sector: "Communication" },
  { ticker: "ICICIBANK.NS", name_kr: "ICICI은행", market: "OTHER", currency: "INR", sector: "Financials" },
  { ticker: "HINDUNILVR.NS", name_kr: "힌두스탄유니레버", market: "OTHER", currency: "INR", sector: "Consumer Staples" },
  { ticker: "BAJFINANCE.NS", name_kr: "바자즈파이낸스", market: "OTHER", currency: "INR", sector: "Financials" },
  { ticker: "ITC.NS", name_kr: "ITC", market: "OTHER", currency: "INR", sector: "Consumer Staples" },
  { ticker: "LT.NS", name_kr: "L&T", market: "OTHER", currency: "INR", sector: "Industrials" },
  { ticker: "ASIANPAINT.NS", name_kr: "아시안페인트", market: "OTHER", currency: "INR", sector: "Materials" },
  { ticker: "MARUTI.NS", name_kr: "마루티스즈키", market: "OTHER", currency: "INR", sector: "Consumer Discretionary" },
  { ticker: "SUNPHARMA.NS", name_kr: "선파마", market: "OTHER", currency: "INR", sector: "Healthcare" },
  { ticker: "NTPC.NS", name_kr: "NTPC", market: "OTHER", currency: "INR", sector: "Utilities" },
  { ticker: "WIPRO.NS", name_kr: "위프로", market: "OTHER", currency: "INR", sector: "Technology" },
  { ticker: "PETR4.SA", name_kr: "페트로브라스", market: "OTHER", currency: "BRL", sector: "Energy" },
  { ticker: "VALE3.SA", name_kr: "발레(브라질)", market: "OTHER", currency: "BRL", sector: "Materials" },
  { ticker: "BBAS3.SA", name_kr: "방코두브라질", market: "OTHER", currency: "BRL", sector: "Financials" },
  { ticker: "CMIG4.SA", name_kr: "세미그", market: "OTHER", currency: "BRL", sector: "Utilities" },
  { ticker: "GMEXICOB.MX", name_kr: "그루포멕시코", market: "OTHER", currency: "MXN", sector: "Materials" },
  { ticker: "CX", name_kr: "세멕스", market: "OTHER", currency: "USD", sector: "Materials" },
  { ticker: "WALMEX.MX", name_kr: "월마트멕시코", market: "OTHER", currency: "MXN", sector: "Consumer Staples" },
  { ticker: "BBD", name_kr: "방코브라데스코(ADR)", market: "OTHER", currency: "USD", sector: "Financials" },
  { ticker: "ABEV", name_kr: "암베브(ADR)", market: "OTHER", currency: "USD", sector: "Consumer Staples" },
  { ticker: "TM", name_kr: "토요타(ADR)", market: "OTHER", currency: "USD", sector: "Consumer Discretionary" },
  { ticker: "SONY", name_kr: "소니(ADR)", market: "OTHER", currency: "USD", sector: "Technology" },
  { ticker: "SE", name_kr: "씨(Sea Limited)", market: "OTHER", currency: "USD", sector: "Communication" },
  { ticker: "GRAB", name_kr: "그랩홀딩스", market: "OTHER", currency: "USD", sector: "Consumer Discretionary" },
  { ticker: "DBSDF", name_kr: "DBS그룹(ADR)", market: "OTHER", currency: "USD", sector: "Financials" },
  { ticker: "D05.SI", name_kr: "DBS그룹", market: "OTHER", currency: "SGD", sector: "Financials" },
  { ticker: "BHP.AX", name_kr: "BHP호주", market: "OTHER", currency: "AUD", sector: "Materials" },
  { ticker: "CBA.AX", name_kr: "CBA은행", market: "OTHER", currency: "AUD", sector: "Financials" },
  { ticker: "CSL.AX", name_kr: "CSL", market: "OTHER", currency: "AUD", sector: "Healthcare" },
  { ticker: "WBC.AX", name_kr: "웨스트팩", market: "OTHER", currency: "AUD", sector: "Financials" },
  { ticker: "SHOP.TO", name_kr: "쇼피파이(캐나다)", market: "OTHER", currency: "CAD", sector: "Technology" },
  { ticker: "RY.TO", name_kr: "캐나다왕립은행", market: "OTHER", currency: "CAD", sector: "Financials" },
  { ticker: "TD.TO", name_kr: "토론토도미니언", market: "OTHER", currency: "CAD", sector: "Financials" },
  { ticker: "ENB.TO", name_kr: "엔브리지", market: "OTHER", currency: "CAD", sector: "Energy" },
  { ticker: "CNQ.TO", name_kr: "캐내디언내추럴리소시스", market: "OTHER", currency: "CAD", sector: "Energy" },
];

export const UNIVERSE_CANDIDATES: UniverseCandidate[] = [...US, ...KR, ...JP, ...CN, ...EU, ...OTHER];
